### ISSUE TITLE
The string for the message can cause "sprintf too few args"

### ISSUE THREAD

**Issue by brennanMKE** [joyent/node-verror#30]
With the message below I found that I get the `sprintf too few args` error. I was returning the path for a REST call which includes % signs which I expect was causing sprintf to experience this error.

```
Requested resource was not found: /v2/resource/1?api_key=API_KEY&append_to_response=abc%2Cxyz%2Cghz%2Cuix%2C&lang=en
```

**Comment by davepacheco** [comment]
If the message itself can contain the "%" character, you have to use "%s".  Instead of:

```javascript
    new VError(str)
```

you would use:

```javascript
    new VError('%s', str)
```

You should do this any time you don't know where "str" came from or if you know it may contain "%".  In your case, this may make sense:

```javascript
    new VError('Requested resource was not found: %s', path)
```

**Comment by itai-codefresh** [comment]
i don't understand why you are not using util.format of node.js which allows this behaviour.
if node.js console.log and util.format allows passing placeholders which in case you didn't provide something to fill them will just continue regullary.
I don't understand why VError should throw an error. i suggest to replace extsprintf to util.format of node.js

**Comment by davepacheco** [comment]
I'm sorry this behavior breaks your programs, but the interface is working as documented and there's a correct way to use it that doesn't have this problem.  Changing this interface would break other people depending on extsprintf features.

**Comment by davepacheco** [comment]
One thing we could do is try to look for the number of "%" expansions and identify whether the arguments are obviously wrong, similar to what we do already do for dealing with potentially null or defined arguments.  At that point, it's looking more appealing to add a less strict mode to node-extsprintf and use that here.

**Comment by davepacheco** [comment]
That said, in the case you've got here, it really seems dangerous.  What if you've mix a URL like the one you have above and also provide an argument?  Wouldn't that corrupt the message?

**Comment by ktrzeciaknubisa** [comment]
I've also encountered such problem, and I was just about to submit a feature request, that we could use an option to disable sprintf completely. 

But then then I just tried escaping a percent sign in a message and it seemed to do the exact thing and my problem was solved.

```js
    VError('Requested resource was not found: /v2/resource/1?api_key=API_KEY&append_to_response=abc%2Cxyz%2Cghz%2Cuix%2C&lang=en)'
        .replace(/%/g, '%%'))
```

**Comment by jclulow** [comment]
In this case, I think you'd be better off using something like:

```
VError('Requested resource was not found: %s',
    '/v2/resource/1?api_key=API_KEY&append_to_response=abc%2Cxyz%2Cghz%2Cuix%2C&lang=en')
```

**Comment by BenSayers** [comment]
My team just got bitten by this in production. This may be documented behavior but this design decision does not follow the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) and has caught us completely by surprise. Having error handling code throw an error because of a % symbol is very undesirable and has made it very difficult for us to work out what is going wrong. I strongly recommend revisiting this design decision or at a minimum create a simple way to disable this behavior in a global way.

**Comment by davepacheco** [comment]
@BenSayers, I'm sorry to hear about the production issue.  I've had that happen as well -- I know it's frustrating.

That said, for many of us that use VError, the current behavior _is_ the least surprising.  Personally, I would find it far more surprising (and frustrating) if the implementation allowed '%' to be ambiguous and attempted to infer what was meant.  That approach can be wrong, too -- but it would result in an implicit, non-fatal failure rather than an explicit, fatal failure.  Because many of us use `--abort-on-uncaught-exception` and debug from the core files, fatal failures tend to be far easier to debug.  In this case, we'd be virtually guaranteed to root-cause the bug in VError caller right away from the core file.   If another bug caused the underlying error in the first place (as I've often found when this case comes up), there's a good chance that we'd be able to debug that, too, since we'd have a core file from precisely the moment of the failure.

On the other hand, if the implementation tried to guess what you meant and got it wrong, it might produce a subtly (but critically) incorrect error message, like reporting the wrong URL that was accessed.  It would be hard to know you'd even hit that bug, and it could be extremely time-consuming to track it down (since people typically exhaust other options before guessing that an error message itself was just wrong).

So there's a tradeoff here.  We made this choice intentionally, and it works well for us.  Of course, I understand that it might not be right for everybody.

It sounds like you spent a lot of time debugging the underlying issue.  If you're not using core files, I can see that you might not have enough information in the exception to know what the problem was. 
 How much would it have helped if sprintf itself had reported more information about the problem, like `too few arguments for format string "$format_string": could not find match for '%' formatter at character $position`?

**Comment by BenSayers** [comment]
We are not using core files or the templating feature provided by VError. I can see how ambiguous % symbols might cause an incorrect error message for those who are using the templating feature however for those who are not this behaviour of throwing an exception provides no value or benefit, which is why I recommended providing a way to globally opt out.

The reason debugging the underlying issue took us so long is VError is masking the underlying exception that led to the situation. If you surfaced this underlying error details as part of the error that is thrown that would have significantly improved the situation.
